  name: Build vcam125 Bypass
  on:
    push:
      branches: [ main ]
    workflow_dispatch:
  env:
    THEOS: /opt/theos
  jobs:
    build:
      runs-on: macos-14
      steps:
        - uses: actions/checkout@v4
        - run: brew install ldid xz
        - name: Clone Theos
          run: |
            sudo git clone --recursive https://github.com/theos/theos $THEOS
            sudo chown -R "$USER" $THEOS
        - name: SDK
          run: |
            curl -L -o sdk.tar.xz https://github.com/theos/sdks/releases/download/master-146e41f/iPhoneOS16.5.sdk.tar.xz
            tar -xf sdk.tar.xz -C $THEOS/sdks/
        - run: make package FINALPACKAGE=1 STRIP=1
        - uses: actions/upload-artifact@v4
          with:
            name: vcam125-bypass-deb
            path: packages/*.deb
            retention-days: 30
